/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'totalRupees' : IDL.Float64,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'settings' : IDL.Record({
    'theme' : IDL.Text,
    'notificationsEnabled' : IDL.Bool,
    'soundEnabled' : IDL.Bool,
  }),
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getRupeesFromPoints' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'jackpot' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'luckyWinner' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scratchCard' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'spinWheel' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'totalRupees' : IDL.Float64,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'settings' : IDL.Record({
      'theme' : IDL.Text,
      'notificationsEnabled' : IDL.Bool,
      'soundEnabled' : IDL.Bool,
    }),
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getRupeesFromPoints' : IDL.Func([IDL.Nat], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'jackpot' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'luckyWinner' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scratchCard' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'spinWheel' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };